Quality = read.csv("Quality.csv")
str(Quality)
table(Quality$PoorCare)
library("caTools")
set.seed(88)
split = sample.split(Quality$PoorCare,SplitRatio = 0.75)
Quality_Train = subset(Quality,split == TRUE)
Quality_Test = subset(Quality,split == FALSE)
nrow(Quality_Test)
nrow(Quality_Train)
names(Quality)
QualityLog = glm(PoorCare ~ OfficeVisits + Narcotics,data = Quality_Train, family = binomial)
summary(QualityLog)
predictTrain = predict(QualityLog,type = "response")
summary(predictTrain)
tapply(predictTrain,Quality_Train$PoorCare, mean)

StartedOnCombination_num = as.numeric(Quality_Train$StartedOnCombination)
QualityLog = glm(PoorCare~StartedOnCombination_num,data = Quality_Train, family = binomial)
summary(QualityLog)
#as.numeric(Quality$StartedOnCombination)
Model = glm(PoorCare ~ StartedOnCombination + ProviderCount, data=Quality_Train, family=binomial)
summary(Model)
table(Quality_Train$PoorCare,predictTrain > 0.5)  # 0.5 is the threshold
table(Quality_Train$PoorCare,predictTrain > 0.7)  # 0.7 is the threshold
table(Quality_Train$PoorCare,predictTrain > 0.2)  # 0.7 is the threshold
library(ROCR)
ROCRpred = prediction(predictTrain,Quality_Train$PoorCare)
ROCRperf = performance(ROCRpred,"tpr","fpr")
plot(ROCRperf,colorize = TRUE,print.cutoffs.at=seq(0,1,0.1),text.adj=c(-0.2,1.7))
QualityLog = glm(PoorCare ~ OfficeVisits + Narcotics,data = Quality_Train, family = binomial)
predictTest = predict(QualityLog, type="response", newdata= Quality_Test)
ROCRpredTest = prediction(predictTest, Quality_Test$PoorCare)
auc = as.numeric(performance(ROCRpredTest, "auc")@y.values)
