getwd()
USDA = read.csv("USDA.csv")
str(USDA)
summary(USDA)
USDA$Sodium
which.max(USDA$Sodium)
names(USDA)
USDA$Description[265]
HighSodium = subset(USDA,Sodium > 10000)
nrow(HighSodium)
HighSodium$Description
match("CAVIAR",USDA$Description)
USDA$Sodium[4154]
summary(USDA$Sodium)
sd(USDA$Sodium)
sd(USDA$Sodium,na.rm=TRUE)
plot(USDA$Protein,USDA$TotalFat,xlab = 'Protein',ylab = 'Fat',main='Title vs Fat',col='red')
hist(USDA$VitaminC,xlab = 'Vitamin C',main = 'Histogram of Vitamin C levels',xlim = c(0,100),breaks = 2000)
boxplot(USDA$Sugar,ylab = 'Sugar in grams',main = 'Boxplot for surgar')
HighSodium = USDA$Sodium > mean(USDA$Sodium,na.rm=TRUE)
HighSodium = as.numeric(HighSodium)
USDA$HighSodium = HighSodium
str(USDA)
USDA$HighProtein = as.numeric(USDA$Protein > mean(USDA$Protein,na.rm= TRUE))
USDA$HighFat = as.numeric(USDA$TotalFat > mean(USDA$TotalFat,na.rm= TRUE))
USDA$HighCarbo = as.numeric(USDA$Carbohydrate > mean(USDA$Carbohydrate,na.rm= TRUE))
str(USDA)
table(USDA$HighSodium)
table(USDA$HighSodium,USDA$HighFat)
tapply(USDA$Iron,USDA$HighProtein,mean,na.rm=TRUE)
tapply(USDA$VitaminC,USDA$HighCarbo,summary,na.rm=TRUE)
